apiVersion: v1
kind: ConfigMap
metadata:
  name: download-microservice-configmap
data:
  postgres_db: "downloaddb"
  redis_host: "queue-service"
  redis_port: "6379"
  redis_queue_name: "purchasedQueue"