apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-postgres
spec:
  selector:
    matchLabels:
      app: download-postgres
  template:
    metadata:
      labels:
        app: download-postgres
    spec:
      containers:
        - name: download-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER # Secret
              valueFrom:
                secretKeyRef:
                  name: download-service-secret
                  key: postgres_username
                  optional: false
            - name: POSTGRES_PASSWORD # Secret
              valueFrom:
                secretKeyRef:
                  name: download-service-secret
                  key: postgres_password
                  optional: false
            - name: POSTGRES_DB # ConfigMap
              valueFrom:
                configMapKeyRef:
                  key: postgres_db
                  name: download-microservice-configmap
          ports:
            - name: postgreport
              containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: download-postgres
spec:
  selector:
    app: download-postgres
  ports:
    - name: postgreport
      port: 5432
      targetPort: postgreport